{"uuid": "4295b592-aaaf-4536-9f5d-0a31d118c2bc", "children": ["7c778461-50a2-4528-a68f-c37be6891a1e"], "befores": [{"name": "setup_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.14.2</center>\r\n</body>\r\n</html>\r\n\n\n", "trace": "  File \"C:\\Users\\K\\qa_guru_10_jenkins\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\K\\qa_guru_10_jenkins\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\K\\qa_guru_10_jenkins\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\K\\qa_guru_10_jenkins\\tests\\conftest.py\", line 44, in setup_browser\n    driver = webdriver.Remote(\n  File \"C:\\Users\\K\\qa_guru_10_jenkins\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\K\\qa_guru_10_jenkins\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\K\\qa_guru_10_jenkins\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\K\\qa_guru_10_jenkins\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 209, in check_response\n    raise exception_class(value)\n"}, "start": 1677169860679, "stop": 1677169860942}], "start": 1677169860679, "stop": 1677169861318}